### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [olgasolda/grid-template#1]
1) Внешний вид не соответствует поставленной задаче.
Сравните результат с макетом или мастер шаблоном.
![image](https://user-images.githubusercontent.com/8464662/224778089-8aaa561b-0407-433c-9dbb-67d8564d1b76.png)
![image](https://user-images.githubusercontent.com/8464662/224778202-604db48b-8cb5-4ef8-b8b7-f302382302f8.png)

**Comment by olgasolda** [comment]
@Alecto Исправила. Не заметила сразу эту ошибку. Добавила width: 100%, в img

![image](https://user-images.githubusercontent.com/123564535/225001386-4521122d-ff77-403d-a6b2-07ed1d9043f9.png)

**Comment by Alecto** [comment]
Для сдачи домашнего задания требуются две ссылки:
1 - на страницу github pages (конечный, видимый результат вашей работы).
2 - на страницу репозитория (ссылка на ваш профиль, на все репозитории -
ошибка).

вт, 14 бер. 2023 р. о 14:31 olgasolda ***@***.***> пише:
